CandleafShop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
    path('', include('cart.urls', namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.shopping_cart, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('subtract/<int:product_id>/', views.subtract_from_cart, name='subtract'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('discovery/<slug:category_slug>/', views.sort_by_category, name='category'),
    path('products/<slug:detail_slug>/', views.detail, name='detail'),
    path('products/', views.discovery, name='discovery'),
    path('test/', views.test, name='test'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.registration, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

theme/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf</title>
    {% tailwind_preload_css %}
    {% tailwind_css %}
    <link type="text/css" href="{% static 'products/css/base.css' %}" rel="stylesheet" />
    {% block css %} {% endblock %}
{#    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />#}
{#    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css' />#}
</head>
<body class="m-0 p-0 bg-pwhite">
<header>
        <nav class="flex flex-row h-[75px] w-full justify-center">
            <div class="flex flex-wrap flex-row h-[75px] justify-between xl:w-[1000px] sm:w-[480px] md:w-[1000px] items-center">
                <div class="flex w-auto h-auto">
                    <a href="{% url 'products:home' %}">
                        <img src="{% static 'products/images/logo.png' %}" class="w-[126px] h-[34px]" alt="Candleaf" />
                    </a>
                </div>
                <div class="flex flex-wrap items-center h-auto md:w-1/3 xl:w-1/3 sm:w-[80px] justify-center">
                    <ul class="flex sm:flex-col md:flex-row xl:flex-row list-none flex-row">
                        <li class="mr-10"><a href="{% url 'products:discovery' %}">Discovery</a></li>
                        <li class="mr-10"><a href="{% url 'products:about' %}">About us</a></li>
                        <li class="mr-10"><a href="">Contacts</a></li>
                    </ul>
                </div>
                <div class="flex w-[100px] h-auto justify-between">
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}">
                            <img src="{% static 'products/images/acc_auth.png' %}" class="w-[34px] h-[34px]" alt="account">
                        </a>
                    {% else %}
                        <a href="{% url 'users:login' %}">
                            <img src="{% static 'products/images/acc.png' %}" class="w-[34px] h-[34px]" alt="account">
                        </a>
                    {% endif %}
                    {% if cart.products.exists %}
                        <a href="{% url 'cart:cart'  %}"><img src="{% static 'products/images/bask_full.png' %}" class=" flex w-[29px] h-[28px]" alt="basket">
                        <p class="relative left-[15px] bottom-[23px] text-white text-[8px]">{{ cart.total_quantity }}</p></a>
                    {% else %}
                        <a href="{% url 'cart:cart'  %}"><img src="{% static 'products/images/bask.png' %}" class="flex w-[29px] h-[28px]" alt="basket"></a>
                    {% endif %}
                </div>
            </div>
        </nav>
</header>

{% block body %} {% endblock %}

<footer class="flex justify-center items-center w-full h-auto bg-dark">
    <div class="flex flex-wrap justify-between items-center mt-[70px] w-4/5 h-auto text-white border-t-[1px] mb-[200px]">
        <div class="flex flex-col items-start justify-start w-[50%] h-[180px]">
            <img src="{% static 'products/images/footer logo.png' %}" class="w-[250px] h-auto" alt="Candleaf">
            <h3>Your natural candle made for<br /> your home and for your wellness.</h3>
        </div>
        <div class="flex w-[50%] h-auto justify-between">
            <div class="h-[300px]">
                <ul class="">
                    <li class="mt-[80px] mb-[35px]"><span class="text-green">Discovery</span></li>
                    <li class="mb-[35px]">New season</li>
                    <li class="mb-[35px]">Most searched</li>
                    <li>Most selled</li>
                </ul>
            </div>
            <div class="h-[300px]">
            <ul>
                <li class="mt-[80px] mb-[35px]"><span class="text-green">About</span></li>
                <li class="mb-[35px]">Help</li>
                <li class="mb-[35px]">Shipping</li>
                <li class="">Affiliate</li>
            </ul>
            </div>
            <div class="h-[300px]">
            <ul>
                <li class="mt-[80px] mb-[35px]"><span class="text-green">Info</span></li>
                <li class="mb-[35px]">Contact us</li>
                <li class="mb-[35px]">Privacy Policies</li>
                <li>Terms & Conditions</li>
            </ul>
            </div>
        </div>
    </div>
</footer>

</body>
</html>