CandleafShop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
    path('', include('cart.urls', namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.shopping_cart, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('subtract/<int:product_id>/', views.subtract_from_cart, name='subtract'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.registration, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users/images', blank=True)

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Enter your password"}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your username"}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your First name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your Last name"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': "Enter your email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Create password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Repeat password"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'read'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'readonly': True, 'class': 'read'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'photo-change-button-input', 'value': 'Change photo', 'type': 'file', 'id': 'file-upload'
    }), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

users/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from django.contrib import auth

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('products:home'))

    else:
        form = UserLoginForm()

    context = {'form': form}
    return render(request, 'users/login.html', context=context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context=context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('products:home')

users/templates/users/login.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/login.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}

<div class="login-container">
    <div class="login-container-child">
        {% if  form.errors %}
            <div class="login-error-container" role="alert">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <form action="{% url 'users:login' %}" method="post" class="login-inputs-container">
            {% csrf_token %}
            <p class="container-title">Sign In</p>
            {{ form.username }}
            {{ form.password }}
            <div class="create-account">
                <button class="create-account-button">
                    <a class="link" href="{% url 'users:register' %}">Create an Account</a>
                </button>
            </div>
            <div class="sign-in">
                <a class="link">
                    <button class="sign-in-button" type="submit">Sign In</button>
                </a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/profile.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="container">
    <div class="container-child">
    <form class="profile-container" action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="photo-container">
            <div class="photo">
                <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'users/images/user-avatar.png' %} {% endif %}" alt="">
            </div>
        </div>
        <label for="file-upload" class="photo-change-button">Change photo</label>
        {{ form.image }}
        <div class="profile-inputs-container">
            <label>First name:</label>
            {{ form.first_name }}
            <label>Last name:</label>
            {{ form.last_name }}
            <label>Email:</label>
            {{ form.email }}
            <label>Username:</label>
            {{ form.username }}
        </div>
            <button class="save-changes" type="submit">Save changes</button>
    </form>
    <div class="log-out-container">
        <a href="{% url 'users:logout' %}"><button class="log-out" >Log out</button></a>
    </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/register.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="register-container">
    <div class="register-container-child">
        {% if form.errors %}
            <div class="error-container" role="alert">
                {{ form.errors }}
            </div>
        {% endif %}
        <form action="{% url 'users:register' %}" method="post" class="register-inputs-container">
            {% csrf_token %}
            <p class="container-title">Create an Account</p>
            {{ form.username }}
            {{ form.first_name }}
            {{ form.last_name }}
            {{ form.email }}
            {{ form.password1 }}
            {{ form.password2 }}
            <div class="sign-in">
                <button class="sign-in-button" >
                    <a class="link" href="{% url 'users:login' %}">Sign In</a>
                </button>
            </div>
            <div class="create-account">
                <button class="create-account-button" type="submit">Create an Account</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}