CandleafShop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
    path('', include('cart.urls', namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.shopping_cart, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('subtract/<int:product_id>/', views.subtract_from_cart, name='subtract'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('discovery/<slug:category_slug>/', views.sort_by_category, name='category'),
    path('products/<slug:detail_slug>/', views.detail, name='detail'),
    path('products/', views.discovery, name='discovery'),
    path('test/', views.test, name='test'),
]

products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    description = models.CharField(max_length=500)
    quantity = models.IntegerField(default=20)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    image = models.ImageField(blank=True, upload_to='products/images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)

    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-quantity']
        indexes = [
            models.Index(fields=['-quantity'])
        ]

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'detail_slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Product, Category
from cart.models import Cart


def index(request):
    products_data = Product.objects.all()
    context = {
        'mainpage_products': products_data[:8],
        'all_products': products_data,
        'popular_products': products_data[:4],
        'my_range': range(5)
    }
    return render(request, 'products/index.html', context=context)


def about(request):
    return render(request, 'products/about.html')


def detail(request, detail_slug):
    slug_detail = get_object_or_404(Product, slug=detail_slug)

    data = {
        'product': slug_detail,
    }
    return render(request, 'products/detail.html', context=data)


def discovery(request):
    products_data = Product.objects.all()
    category = Category.objects.all()
    context = {
        'all_products': products_data,
        'category': category
    }
    return render(request, 'products/discovery.html', context=context)


def sort_by_category(request, category_slug):
    category_info = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category_info)
    category = Category.objects.all()
    context = {
        'category_info': category_info,
        'category': category,
        'products': products
    }
    return render(request, 'products/category.html', context)


def test(request):
    return render(request, 'products/test.html')

products/templates/products/about.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/about.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="flex flex-col justify-center items-center">
    <div class="w-full max-w-[1000px] mt-[50px] h-auto mb-[50px] ml-[20px] mr-[20px]">
        <p>
            <span class="font-semibold">Candleaf</span> is an enchanting boutique nestled in a charming corner of the city, dedicated
            to the art and craft of candle making. As soon as you step into <span class="font-semibold">Candleaf</span>, you're greeted
            by a warm, inviting atmosphere that immediately relaxes you. The walls are painted in soothing
            earth tones, and there's a gentle, subtle scent in the air – a blend of lavender, vanilla,
            and a hint of sandalwood.
        </p>
        <br/>
        <p>
            The shop features an extensive array of candles, each one handcrafted with meticulous care.
            The range includes everything from small, delicate tealights perfect for a cozy dinner table to large,
            statement pillar candles that can be the centerpiece of any room. The candles come in various shapes and
            sizes, and the variety of colors is a feast for the eyes - from deep, rich reds and blues to soft pastels
            and natural beeswax hues.
        </p>
        <br/>
        <p>
            One of the highlights of <span class="font-semibold">Candleaf</span> is its selection of scented candles.
            These candles are made with natural essential oils and offer an array
            of fragrances, from the refreshing zest of citrus to the sweet allure
            of summer berries. Seasonal scents are also available, ensuring there's
            always something new to discover.
        </p>
        <br/>
        <p>
            In addition to candles, <span class="font-semibold">Candleaf</span> also offers a range of candle-related accessories,
            such as elegant holders, snuffers, and wick trimmers, all designed to enhance your
            candle-burning experience.
        </p>
        <br/>
        <p>
            <span class="font-semibold">Candleaf</span> isn't just a store; it's a haven for candle enthusiasts. The staff are knowledgeable and passionate
            about their craft. They offer workshops where customers can learn the art of candle making, from the basics
            of wax selection and scent blending to the skills needed to create beautifully layered candles.
        </p>
        <br/>
        <p>
            The shop also has a commitment to sustainability. They use eco-friendly materials and
            processes wherever possible, and many of their products are made from recycled or renewable resources.
        </p>
        <br/>
        <p>
            <span class="font-semibold">Candleaf</span> is more than just a place to buy candles. It's an experience, a place where you can slow down,
            breathe in the tranquil atmosphere, and find the perfect candle to light up your life.
            Whether you're a candle aficionado or new to the world of candles, <span class="font-semibold">Candleaf</span> welcomes you with open
            arms and a flickering flame.
        </p>
    </div>
</div>
{% endblock %}

products/templates/products/category.html
{% extends 'base.html'%}
{% load static %}

{% block body %}
<div class="flex flex-wrap justify-center items-center w-full h-auto">
    <div class="flex flex-wrap justify-center items-center w-[1300px] h-auto mt-[50px] ">
        <ul class="flex flex-row justify-between">
            <li class="mr-[20px]">Categories:</li>
            <a href="{% url 'products:discovery' %}"><li class="mr-[20px]">All</li></a>
            {% for type in category %}
            <a href="{% url 'products:category' type.slug %}"><li class="mr-[20px]">{{ type.name }}</li></a>
            {% endfor %}
        </ul>

    </div>
    <div class="flex flex-wrap justify-center items-center w-full h-auto">
        <div class="flex flex-wrap justify-center items-center w-full h-auto mb-[50px]">
            {% for product in products %}
            {% include 'products/includes/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/detail.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/detail.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="detail-container">
    <div class="detail-img">
        <img class="product-img" src="{{ product.image.url }}" alt="{{ product.name }}">
        <p>All hand-made with natural soy wax, Candleaf is <br>made for your pleasure moments.</p>
        <h1>🚚 FREE SHIPPING</h1>
    </div>
    <div class="detail-purchase">
        <h1>{{ product.name }} Candleaf&#174;</h1>
        <div class="purchase-container">
            <div class="price-quantity">
                <div class="price"><h1>{{ product.price }}$</h1></div>
                <div class="quantity"></div>
            </div>
            <div class="purchase-choices">
                <ul>
                    <li><span>Wax:</span> Top grade Soy wax that delivers a smoke less, consistent burn</li>
                    <li><span>Fragrance:</span> Premium quality ingredients with natural essential oils</li>
                    <li><span>Burning Time:</span> 70-75 hours</li>
                    <li><span>Dimension:</span> 10cm x 5cm</li>
                    <li><span>Weight:</span> 400g</li>
                </ul>
            </div>
        </div>
        <a href="{% url 'cart:add' product.id %}"><button class="add-to-cart">Add to cart</button></a>
        <div class="product-description">
            <p>{{ product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/discovery.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/discovery.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="flex flex-wrap justify-center items-center w-full h-auto">
    <div class="flex flex-wrap justify-center items-center w-[1300px] h-auto mt-[50px] ">
        <ul class="flex flex-row justify-between">
            <li class="mr-[20px]">Categories:</li>
            <a href="{% url 'products:discovery' %}"><li class="mr-[20px]">All</li></a>
            {% for type in category %}
            <a href="{% url 'products:category' type.slug %}"><li class="mr-[20px]">{{ type.name }}</li></a>
            {% endfor %}
        </ul>

    </div>
    <div class="flex flex-wrap justify-center items-center w-full h-auto">
        <div class="flex flex-wrap justify-center items-center w-full h-auto mb-[50px]">
            {% for product in all_products %}
            {% include 'products/includes/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/index.html
{% extends 'base.html'%}
{% load static %}
{% load tailwind_tags %}

{% block css %}
<link type="text/css" href="{% static 'products/css/index.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="flex flex-wrap flex-col">
    <div class="flex flex-wrap items-center justify-center w-full h-1/5">
        <img src="{% static 'products/images/fullimg.png' %}" alt="candleaf" class="w-full h-auto"/>
        <div class="absolute flex flex-col items-center justify-center top-1/5 bg-white/80 xl:w-[700px] xl:h-[350px] md:w-[560px] md:h-[280px] sm:w-[420px] sm:h-[210px] backdrop-opacity-20">
            <h1 class="xl:text-[50px] font-semibold sm:text-[30px]">🌱</h1>
            <h1 class="text-[#1D252C] xl:text-[50px]  md:text-[40px] sm:text-[30px]">The nature candle</h1>
            <h3 class="text-[#1D252C] xl:text-[20px] md:text-[18px] sm:text-[13px]">All handmade with natural soy wax, Candleaf is a companion for all your pleasure moments </h3>
            <button id="discoveryButton" data-static-url="{% url 'products:discovery' %}" class="w-1/2 h-[13%] bg-green hover:bg-dgreen text-white sm:text-[16px] md:text-[20px] xl:text-[25px] border-none rounded-sm mt-[10px]">Discovery our collection</button>
        </div>
    </div>
    <div class="flex flex-col items-center justify-center w-full h-[200px]">
        <h1 class="text-5xl font-semibold">Products</h1>
        <h3 class="text-[#5E6E89] font-medium">Order it for you or for your beloved ones </h3>
    </div>
    <div class="flex flex-wrap justify-center items-center w-full h-auto ">
        <div class="flex flex-wrap justify-center items-center max-w-[1300px] w-full h-auto mb-[100px]">
            {% for product in mainpage_products %}
            {% include 'products/includes/product.html' %}
            {% endfor %}
        </div>
    </div>
    <div class="flex flex-wrap justify-center w-full h-auto bg-white">
        <div class="flex flex-wrap max-w-[1100px] justify-between items-center w-full min-h-[600px] h-auto bg-white mb-[50px]">
            <div class="flex flex-wrap flex-col w-[500px] h-auto ml-[50px] mb-[50px] mt-[50px]">
                <h1 class="text-[40px] leading-none">Clean and</h1>
                <h1 class="text-[40px] leading-none">fragrant soy wax</h1>
                <p class="text-[16px] mt-[20px] text-green">Made for your home and for your wellness</p>
                <ul class="mt-[40px] leading-normal">
                    <li class="pl-8 mb-[15px]" style="background-image: url(/products/images/galochka.svg); background-size: 1.4rem 1.4rem;"><span>Eco-sustainable: </span>All recyclable materials, 0% CO2 emissions</li>
                    <li class="pl-8 mb-[15px]" style="background-image: url(/products/images/galochka.svg); background-size: 1.4rem 1.4rem;"><span>Hyphoallergenic: </span>100% natural, human friendly ingredients </li>
                    <li class="pl-8 mb-[15px]" style="background-image: url(/products/images/galochka.svg); background-size: 1.4rem 1.4rem;"><span>Handmade: </span>All candles are craftly made with love.</li>
                    <li class="pl-8 mb-[15px]" style="background-image: url(/products/images/galochka.svg); background-size: 1.4rem 1.4rem;"><span>Long burning: </span>No more waste. Created for last long.</li>
                </ul>
                <button id="aboutButton" data-static-url="{% url 'products:about' %}" class="w-[200px] h-[40px] bg-green text-white text-[20px] rounded-[3px] border-none mt-[50px] ml-[25%] hover:bg-dgreen">Learn more</button>
            </div>
            <div class=" flex w-[480px] h-auto justify-center items-center">
                <img src="{% static 'products/images/info.png' %}" alt="candleaf">
            </div>
        </div>
    </div>
    <div class="flex flex-wrap w-full justify-center items-center bg-[#56b27f23]">
        <div class="flex flex-col w-full h-auto justify-center items-center mt-[50px] mb-[50px]">
            <h1 class="text-5xl font-semibold">Testimonials</h1>
            <h3 class="text-[#5E6E89] font-medium">Some quotes from our happy customers</h3>
        </div>
        <div class="flex flex-wrap w-full max-w-[1300px] h-auto justify-center items-center mb-[50px]">
            <div class="flex flex-col w-[350px] h-[320px] m-[15px] bg-pwhite rounded-[4px] justify-center items-center">
                <img class="flex w-[140px] h-auto" src="{% static 'products/images/luisa.png' %}" alt="Luisa">
                <div class="flex flex-wrap w-[150px] h-[25px] items-center justify-center mb-[10px]">
                    {% include 'products/includes/stars.html' %}
                </div>
                <h1 class="text-[22px]">“I love it! No more air</h1>
                <h1 class="text-[22px]">fresheners”</h1>
                <h3 class="text-[20px] text-[#5E6E89]">Luisa</h3>
            </div>
            <div class="flex flex-col w-[350px] h-[320px] m-[15px] bg-pwhite rounded-[4px] justify-center items-center">
                <img class="flex w-[140px] h-auto" src="{% static 'products/images/eduardo.png' %}" alt="Eduardo">
                <div class="flex flex-wrap w-[150px] h-[25px] items-center justify-center mb-[10px]">
                    {% include 'products/includes/stars.html' %}
                </div>
                <h1 class="text-[22px]">“Raccomended for </h1>
                <h1 class="text-[22px]">everyone”</h1>
                <h3 class="text-[20px] text-[#5E6E89]">Edoardo</h3>
            </div>
            <div class="flex flex-col w-[350px] h-[320px] m-[15px] bg-pwhite rounded-[4px] justify-center items-center">
                <img class="flex w-[140px] h-auto" src="{% static 'products/images/mart.png' %}" alt="Mart">
                <div class="flex flex-wrap w-[150px] h-[25px] items-center justify-center mb-[10px]">
                    {% include 'products/includes/stars.html' %}
                </div>
                <h1 class="text-[22px]">“Looks very natural, the</h1>
                <h1 class="text-[22px]"> smell is awesome”</h1>
                <h3 class="text-[20px] text-[#5E6E89]">Mart</h3>
            </div>
        </div>
    </div>

    <div class="flex flex-wrap flex-col justify-center items-center w-full h-auto">
        <h1 class="text-5xl font-semibold mt-[50px]">Popular</h1>
        <h3 class="text-[#5E6E89] font-medium mb-[20px]">Our top selling product that you may like</h3>
        <div class="flex flex-wrap w-full max-w-[1300px] h-auto justify-center items-center mb-[50px]">
            {% for product in popular_products %}
            {% include 'products/includes/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
<script src="{% static 'products/js/index.js' %}"></script>
{% endblock %}

products/templates/products/test.html
{% extends 'base.html'%}
{% load static %}

{% block body %}
<div id="div-id"></div>
<p>Хуй собачий добрій день</p>
<script src="{% static 'products/js/test.js' %}"></script>
{% endblock %}